repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        entry: ruff check --fix
        types: [python]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - dbt-core
          - dbt-duckdb
          - sqlfluff-templater-dbt
        env:
          DBT_PROFILES_DIR: dbt

  - repo: local
    hooks:
      - id: dbt-parse
        name: dbt parse
        entry: dbt parse --project-dir dbt --profiles-dir dbt
        language: system
        pass_filenames: false
        env:
          DBT_PROFILES_DIR: dbt
